security:
  basic:
    enabled: false # turn off securing app endpoints

management:
  security:
    enabled: false # turn off securing actuator endpoints

logging:
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: true

quoteSerivceURL: http://quote-service-dev.cfapps.io/quote